add_newline = false
palette = "custom"

format = """
[╭─](bold fg:primary)$username[🭬](bold bg:secondary fg:primary)$hostname[🭬](bold bg:primary fg:secondary)$directory[](bold fg:primary)$fill[](bold fg:secondary)$shell[🭮](bold bg:secondary fg:primary)$time[](bold fg:primary)
[╰─\\[](bold fg:primary)$character[\\]─](bold fg:primary)[λ](fg:lambda) 
"""

[palettes.custom]
primary = "#8caaee"
secondary = "#9cbbff"
lambda = "#c49bc4"
success = "#b0d59a"
error = "#d67a82"

[username]
format = "[ $user ](bg:primary fg:black)"
show_always = true
style_user = "bg:primary fg:black"

[hostname]
format = "[ $hostname ](bg:secondary fg:black)"
ssh_only = false

[directory]
format = "[ $path](bg:primary fg:black)"
truncation_length = 3
truncate_to_repo = true

[fill]
symbol = "─"
style = "bold fg:primary"

[shell]
format = "[ $indicator](bg:secondary fg:black)"
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
disabled = false

[time]
format = "[  $time](bg:primary fg:black)[](fg:primary)"
time_format = "%H:%M"
disabled = false

[character]
success_symbol = "[](fg:success)"
error_symbol = "[](fg:error)"
format = "$symbol"

