##################################################
##  _   _                  _                 _  ##
## | | | |_   _ _ __  _ __| | __ _ _ __   __| | ##
## | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | ##
## |  _  | |_| | |_) | |  | | (_| | | | | (_| | ##
## |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| ##
##        |___/|_|                              ##
##################################################
## Config from c1ph3rD0ts by c1ph3rC4t          ##
##################################################

# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = NVD_BACKEND,direct

env = XCURSOR_SIZE,$cursorSize
env = XCURSOR_THEME,$cursorTheme
env = HYPRCURSOR_SIZE,$cursorSize
env = HYPRCURSOR_THEME,$cursorTheme

env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CONFIG_DIRS,$HOME/.config/kdedefaults:/etc/xdg
env = XDG_CONFIG_HOME,$HOME/.config
env = XDG_DATA_HOME,$HOME/.local/share
env = XDG_STATE_HOME,$HOME/.local/state
env = XDG_CACHE_HOME,$HOME/.cache
env = XDG_DESKTOP_DIR,$HOME/Desktop
env = XDG_DOWNLOAD_DIR,$HOME/Downloads
env = XDG_TEMPLATES_DIR,$HOME/Templates
env = XDG_PUBLICSHARE_DIR,$HOME/Public
env = XDG_DOCUMENTS_DIR,$HOME/Documents
env = XDG_MUSIC_DIR,$HOME/Music
env = XDG_PICTURES_DIR,$HOME/Pictures
env = XDG_VIDEOS_DIR,$HOME/Videos

env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = XDG_MENU_PREFIX,arch-

env = GDK_BACKEND,wayland,x11
env = GTK_THEME,catppuccin-frappe-sapphire-standard+default

env = TERMINAL,kitty
